<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <AnalysisLevel>10.0-Recommended</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <DotNetRuntimeTfm>net10.0</DotNetRuntimeTfm>
  </PropertyGroup>
</Project>
