// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodegenTools.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Query : QueryTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("﻿");
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Runtime.Serializat" +
                    "ion;\r\n\r\nnamespace ");
            
            #line 10 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture($"{Namespace}.Service.{Group}"));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 12 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"

if (IsList)
{

            
            #line default
            #line hidden
            this.Write("    // TODO: Don\'t forget to add the corresponding ProtoInclude attribute to the " +
                    "base class!\r\n");
            
            #line 17 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"

}

            
            #line default
            #line hidden
            this.Write("    [DataContract]\r\n    public class ");
            
            #line 21 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture($"{Name}Query"));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 21 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetQueryBaseType(GetResultType())));
            
            #line default
            #line hidden
            
            #line 21 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(IsEventProducer ? ", IEventProducerQuery" : ""));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        [DataMember(Order = 1)] public string Property { get; set; } = n" +
                    "ull!;\r\n");
            
            #line 24 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"

if (IsEventProducer)
{

            
            #line default
            #line hidden
            this.Write("\r\n        public Action<IQuery, Event>? OnEvent { get; set; }\r\n");
            
            #line 30 "D:\Dev\_Templates\AspNetSkeleton\tools\CodegenTools\Templates\Query.tt"

}

            
            #line default
            #line hidden
            this.Write("    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
